blank_issues_enabled: false
contact_links:
  - name: Dynamous Community
    url: https://community.dynamous.ai
    about: Please ask questions and start conversations about the AI Agent Mastery course in our community!